### ISSUE TITLE
The get_user method seem return inconsistent data

### ISSUE THREAD

**Issue by silverwolfceh** [vgrichina/fast-near#16]
I play the hearwallethot on telegram: https://t.me/herewalletbot/app?startapp=4222126

When I claim, the UI update the amount but when I check with get_user method, it seem return the old data:  https://rpc.web4.near.page/account/game.hot.tg/view/get_user?account_id=rokbotsxyz.tg
![2024-06-05_20h08_47](https://github.com/fastnear/fast-near/assets/7804860/76ca72be-aa92-416d-9ef0-c6fb258a3861)
![2024-06-05_20h09_21](https://github.com/fastnear/fast-near/assets/7804860/cb9b7025-772f-4e6b-bc4f-21ab22414553)

**Comment by silverwolfceh** [comment]
To be sure, I wait at least 30 mins but seem the data return from rpc.web4.near still not get update

**Comment by vgrichina** [comment]
@silverwolfceh is this still a problem? 

sometimes data sync fails/lags, see https://web4.betteruptime.com

**Comment by silverwolfceh** [comment]
I think it is resolved right now. Thank you very much
