### ISSUE TITLE
Automatic restart based on the latest block in Redis

### ISSUE THREAD

**Issue by chefsale** [vgrichina/fast-near#3]
In case all indexers go down, ideally we would want to have a restart from latest block height stored in Redis.

**Comment by vgrichina** [comment]
I believe this is implemented here:
https://github.com/vgrichina/near-state-indexer/blob/53fd14b2896182f8a051d8a31cc0beef295a6b8f/src/main.rs#L155

**Comment by chefsale** [comment]
Let's close the issue
